from fuzzers.aflplusplus import fuzzer as aflplusplus_fuzzer
import os
from fuzzers.aflplusplus_ast_opt_base.fuzzer import build_base_opt
# This is essentially O3, with a few Flags taken out: 
        # --loop-unroll\
        # --loop-vectorize\
        # --loop-simplify\
        # --slp-vectorizer\
        # --aggressive-instcombine\
        # --simplifycfg\

def build():
    """Build benchmark."""
    os.environ['AFL_DONT_OPTIMIZE'] = '1'
    os.environ['AST_OPT_FLAGS'] = """
        --tti\
        --tbaa\
        --scoped-noalias\
        --assumption-cache-tracker\
        --targetlibinfo\
        --verify\
        --ee-instrument\
         \
        --domtree\
        --sroa\
        --early-cse\
        --lower-expect\
        --targetlibinfo\
        --tti\
        --tbaa\
        --scoped-noalias\
        --assumption-cache-tracker\
        --profile-summary-info\
        --forceattrs\
        --inferattrs\
        --domtree\
        --ipsccp\
        --called-value-propagation\
        --attributor\
        --globalopt\
        --domtree\
        --mem2reg\
        --deadargelim\
        --domtree\
        --basicaa\
        --aa\
        --loops\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
         \
        --basiccg\
        --globals-aa\
        --prune-eh\
        --inline\
        --functionattrs\
        --argpromotion\
        --domtree\
        --sroa\
        --basicaa\
        --aa\
        --memoryssa\
        --early-cse-memssa\
        --speculative-execution\
        --basicaa\
        --aa\
        --lazy-value-info\
        --jump-threading\
        --correlated-propagation\
         \
        --domtree\
        --basicaa\
        --aa\
        --loops\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
        --libcalls-shrinkwrap\
        --loops\
        --branch-prob\
        --block-freq\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --pgo-memop-opt\
        --basicaa\
        --aa\
        --loops\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --tailcallelim\
         \
        --reassociate\
        --domtree\
        --loops\
        -- \
        --lcssa-verification\
        --lcssa\
        --basicaa\
        --aa\
        --scalar-evolution\
        --loop-rotate\
        --memoryssa\
        --licm\
        --loop-unswitch\
         \
        --domtree\
        --basicaa\
        --aa\
        --loops\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
        -- \
        --lcssa-verification\
        --lcssa\
        --scalar-evolution\
        --indvars\
        --loop-idiom\
        --loop-deletion\
        --mldst-motion\
        --phi-values\
        --basicaa\
        --aa\
        --memdep\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --gvn\
        --phi-values\
        --basicaa\
        --aa\
        --memdep\
        --memcpyopt\
        --sccp\
        --demanded-bits\
        --bdce\
        --basicaa\
        --aa\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
        --lazy-value-info\
        --jump-threading\
        --correlated-propagation\
        --basicaa\
        --aa\
        --phi-values\
        --memdep\
        --dse\
        --basicaa\
        --aa\
        --memoryssa\
        --loops\
         
        --lcssa-verification\
        --lcssa\
        --scalar-evolution\
        --licm\
        --postdomtree\
        --adce\
        --domtree\
        --basicaa\
        --aa\
        --loops\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
        --barrier\
        --elim-avail-extern\
        --basiccg\
        --rpo-functionattrs\
        --globalopt\
        --globaldce\
        --basiccg\
        --globals-aa\
        --domtree\
        --float2int\
        --lower-constant-intrinsics\
        --domtree\
        --loops\
         
        --lcssa-verification\
        --lcssa\
        --basicaa\
        --aa\
        --scalar-evolution\
        --loop-rotate\
        --loop-accesses\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --loop-distribute\
        --branch-prob\
        --block-freq\
        --scalar-evolution\
        --basicaa\
        --aa\
        --loop-accesses\
        --demanded-bits\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --scalar-evolution\
        --aa\
        --loop-accesses\
        --lazy-branch-prob\
        --lazy-block-freq\
        --loop-load-elim\
        --basicaa\
        --aa\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
         \
        --domtree\
        --loops\
        --scalar-evolution\
        --basicaa\
        --aa\
        --demanded-bits\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
         
        --lcssa-verification\
        --lcssa\
        --scalar-evolution\
         \
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --instcombine\
        --memoryssa\
         
        --lcssa-verification\
        --lcssa\
        --scalar-evolution\
        --licm\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --transform-warning\
        --alignment-from-assumptions\
        --strip-dead-prototypes\
        --globaldce\
        --constmerge\
        --domtree\
        --loops\
        --branch-prob\
        --block-freq\
         
        --lcssa-verification\
        --lcssa\
        --basicaa\
        --aa\
        --scalar-evolution\
        --block-freq\
        --loop-sink\
        --lazy-branch-prob\
        --lazy-block-freq\
        --opt-remark-emitter\
        --div-rem-pairs\
        --callsite-splitting\
        --verify\
        --instsimplify\
    """
    build_base_opt()


def fuzz(input_corpus, output_corpus, target_binary):
    """Run fuzzer."""
    run_options = []
    aflplusplus_fuzzer.fuzz(input_corpus,
                            output_corpus,
                            target_binary,
                            flags=(run_options))
